---
# ECR Credential Helper
- name: ecr-credential-helper|Install Amazon ECR Credential Helper
  yum:
    #lock_timeout: 180
    name:
      - "amazon-ecr-credential-helper"
    state: present

- name: ecr-credential-helper|Get AWS Account ID (for cred helper config.json)
  uri:
    url: http://169.254.169.254/latest/meta-data/identity-credentials/ec2/info
    return_content: yes
  register: aws_account_id_output
  failed_when: "'AccountId' not in aws_account_id_output.content"

- debug:
    msg: "Account ID Found: {{ aws_account_id_output.content | from_json | json_query('AccountId') }}"

- name: ecr-credential-helper|Create docker dir for ECR credential helper
  file:
    path: "{{ item.user_home }}/.docker"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0700
  with_items:
    - { user: "ec2-user", user_home: "/home/ec2-user" }
    - { user: "gitlab-runner", user_home: "/home/gitlab-runner" }
    - { user: "root", user_home: "/root" }

- name: ecr-credential-helper|Deploy config.json for ECR credential helper
  template:
    src: "docker-ecr-cred-helper-config.j2"
    dest: "{{ item.user_home }}/.docker/config.json"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: 0600
  with_items:
    - { user: "ec2-user", user_home: "/home/ec2-user" }
    - { user: "gitlab-runner", user_home: "/home/gitlab-runner" }
    - { user: "root", user_home: "/root" }
...
