---
- name: gitlab-runner-software|Add Repo
  yum_repository:
    name: runner_gitlab-runner
    description: runner_gitlab-runner
    baseurl: https://packages.gitlab.com/runner/gitlab-runner/el/7/$basearch
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.gitlab.com/gpg.key
      - https://packages.gitlab.com/runner/gitlab-runner/gpgkey/runner-gitlab-runner-366915F31B487241.pub.gpg

- name: gitlab-runner-software|Add GPG Keys for Repo
  rpm_key:
    state: present
    key: https://packages.gitlab.com/gpg.key
  register: add_gitlab_gpg_key

# Update yum cache and accept new keys if added
- name: gitlab-runner-software|Update repo cache for gitlab runner
  command: yum -y makecache fast --disablerepo=* --enablerepo=runner_gitlab-runner
  args:
    warn: false
  when: add_gitlab_gpg_key is changed

- name: gitlab-runner-software|Install GitLab Runner
  yum:
    name: gitlab-runner
    state: installed

- name: gitlab-runner-software|Adding gitlab-runner user to docker group
  user:
    name: gitlab-runner
    groups: docker
    append: yes

- name: gitlab-runner-software|Start and enable gitlab-runner service
  service:
    name: "gitlab-runner"
    state: started
    enabled: yes
...
